### ISSUE TITLE
problem with skolmat after upgrade to 1.5.1

### ISSUE THREAD

**Issue by DariBer** [Kaptensanders/skolmat#16]
When I upgraded skolmat from 1.5.0 to 1.5.1 it stopped to work, when I go back to 1.5.0 it starts to work again.
I have tried these 2 in configuration.yaml file

```
sensor:
  - platform: skolmat
    name: Hägerstensåsens Skola # Name of school here
    rss: "https://skolmaten.se/hagerstensasens-skola/"
```
and

```
sensor:
  - platform: skolmat
    name: Hägerstensåsens Skola # Name of school here
    rss: "https://skolmaten.se/skutehagens-skolan/rss/weeks"
```
I'm running version: 2025.01.3 of Home Assistant
