### ISSUE TITLE
Skolmaten change something?

### ISSUE THREAD

**Issue by bjornenvall** [Kaptensanders/skolmat#17]
Since Friday the integration is broken. I think skolmaten change their rss feed..

**Comment by Kaptensanders** [comment]
Yes, I requested a client token, lets hope for the best

**Comment by Kaptensanders** [comment]
fixed thanks to @I-am-a-node, update to last release

**Comment by Hellis81** [comment]
> fixed thanks to [@I-am-a-node](https://github.com/I-am-a-node), update to last release

Did you get a token from them?
I sent them an email and have not yet got a reply

**Comment by I-am-a-node** [comment]
@Hellis81  - I've done some testing and you don't need one (might in the future). Are you getting blocked? 
They haven't replied to my request either... yet.

**Comment by Hellis81** [comment]
I can't use it.
I get "route not found" or error with client token.
So you are using it without any token?

**Comment by I-am-a-node** [comment]
@Hellis81  Am using without. How does your weblink looks like? Its a bit confusing with the read me and instructions as it shows an old link format. This has to be changed, updated in the provided description for setup.

**Comment by Hellis81** [comment]
I tried this for example:

```
sensor:
  - platform: rest
    name: Skolmaten provinces
    resource_template: "https://skolmaten.se/api/4/provinces"
    method: GET
    value_template: '1'  
    json_attributes:
      - "provinces"
    scan_interval: 86400 
```

But I get this:

![Image](https://github.com/user-attachments/assets/6272080a-95a6-4374-857c-c18baa73aba2)


When I use this tool: https://reqbin.com/
I get this result:

![Image](https://github.com/user-attachments/assets/3d4bf03f-eb39-4d48-a514-fafbcb95aff0)

Who did you do it?

**Comment by I-am-a-node** [comment]
@Hellis81 Oki, I don't know what you're trying to do. Haven't studied the code yet so don't know how that will fit or work with this integration. I don't think @Kaptensanders structured this integration to pull the province. Its is structured to pull a specific school's menu meaning your sensor need to look like this, as in the description

`sensor:
  - platform: skolmat
    name: Skutehagen # Name of school here
    url: "https://skolmaten.se/menu/29f13515-185f-4df5-b39b-bca0a2bc4fc8?school=157fa289-ef68-411d-b2b5-d98014555c02" # url to your school like this
    unique_id: "my_skolmat_sensor" # Optional, better for managing entities, but will change the entity type.
`
The url with the menu code and school will appear in the URL field when navigating to your school site on skolmat.se. Find your schools menu this week and copy the url.

If you are creating your own API you need to add the headers to your http GET request

`headers = {
    'Content-Type': 'application/json',
    'Referer': 'https://skolmaten.se/'
};`

**Comment by Hellis81** [comment]
I'm only trying to create a rest sensor just like I had before. Nothing with the integration. I didn't even know this existed. 

I managed to get provinces to work now.

But when I try with school menu it doesn't seem to work.

```
senor:
  - platform: rest
    name: Skolmaten provinces
    resource_template: "https://skolmaten.se/api/4/menu/15c03250-fbcd-45fc-b350-a885819caa75?year=2025&week=8"
    method: GET
    headers: { 'Content-Type': 'application/json', 'Referer': 'https://skolmaten.se/' }
    value_template: "{{json.value}}"  
    json_attributes:
      - "Days"
    scan_interval: 86400 
```

so the URL to the school is https://skolmaten.se/menu/2840b09d-8db1-406e-9446-ad0d3cefafe7?school=15c03250-fbcd-45fc-b350-a885819caa75
And I assume it's the school parameter that should be in the request? And I'm trying to get the "Days" column.
