### ISSUE TITLE
Skolmaten calender enty

### ISSUE THREAD

**Issue by droidgren** [Kaptensanders/skolmat#21]
In addition to the regular skolmaten sensor it would be nice to also have an calendar entity with Skolmaten entries.

Eg.

calendar.skolmaten
  message: Pasta Alfredo
  all_day: true
  start_time: 2025-03-19 00:00:00
  end_time: 2025-03-20 00:00:00
  location: 
  description: 
  offset_reached: false
  friendly_name: Skolmaten

**Comment by Kaptensanders** [comment]
nice idea, I never even thought of it.

**Comment by droidgren** [comment]
Yes, then you can use the calendar integration to view them. And all entries are also saved in the calendar so you can look back in time, which can be useful sometimes.

![Image](https://github.com/user-attachments/assets/bab6e07c-bb5c-47fb-a2bc-32e2d1e424cb)

**Comment by Kaptensanders** [comment]
i'll look into it and add it. And I need to start using the calendar :P

**Comment by rodakswe** [comment]
That would be soooo great, specially if the events could be added to a Google calendar. 
Before IST(skolmaten) went nuts we had the ical in our Google calendars and every morning our kids asked the Google Assistant "What's on my calendar today?" And it replied with the all day event telling them what they will have for lunch. 
Also me and my wife checked our calendars regularly to see what's in school to not have similar food for dinner in the evening.
Our entire family will be so thankful if we could get the functionality back 😊

**Comment by droidgren** [comment]
> That would be soooo great, specially if the events could be added to a Google calendar. Before IST(skolmaten) went nuts we had the ical in our Google calendars and every morning our kids asked the Google Assistant "What's on my calendar today?" And it replied with the all day event telling them what they will have for lunch. Also me and my wife checked our calendars regularly to see what's in school to not have similar food for dinner in the evening. Our entire family will be so thankful if we could get the functionality back 😊

In the mean the you can use this automation which populates a calendar with Skolmaten entries.
Update `sensor.change.to.your.skolmaten.entity` and `calendar.skolmaten`
```
alias: Update School Menu Calendar
description: Populates calendar.skolmaten with meal data from sensor.soldatangens_forskola
triggers:
  - entity_id: sensor.change.to.your.skolmaten.entity
    trigger: state
conditions: []
actions:
  - variables:
      menu_data: "{{ state_attr('sensor.change.to.your.skolmaten.entity', 'calendar') }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ menu_data is not none }}"
        sequence:
          - repeat:
              for_each: "{{ menu_data.values() | list | sum(start=[]) }}"
              sequence:
                - variables:
                    start_date: "{{ repeat.item.date }}"
                    end_date: >-
                      {{ (repeat.item.date | as_datetime +
                      timedelta(days=1)).date() }}
                - target:
                    entity_id: calendar.skolmaten
                  data:
                    start_date_time: "{{ start_date }} 00:00:00"
                    end_date_time: "{{ end_date }} 00:00:00"
                  response_variable: existing_events
                  action: calendar.get_events
                - variables:
                    event_list: >-
                      {{ existing_events['calendar.skolmaten']['events'] |
                      default([]) }}
                - data:
                    title: "Debug: Calendar Events"
                    message: >-
                      {{ start_date }}: {{ event_list }} => {{ event_list |
                      count == 0 }}
                  action: persistent_notification.create
                  enabled: false
                - if:
                    - condition: template
                      value_template: |
                        {{ event_list | count == 0 }}
                  then:
                    - target:
                        entity_id: calendar.skolmaten
                      data:
                        summary: "{{ repeat.item.courses | join(', ') | capitalize }}"
                        description: >-
                          Måltid på {{
                          state_attr('sensor.change.to.your.skolmaten.entity', 'name') }}
                        start_date: "{{ start_date }}"
                        end_date: "{{ end_date }}"
                      action: calendar.create_event
mode: parallel
```
