### ISSUE TITLE
unique_id not working?

### ISSUE THREAD

**Issue by oscarb** [Kaptensanders/skolmat#24]
To start off with, this solves so many discussions around the dinner table at home, so big thank you! :) 

So my issue then, for some reason even though I've set `unique_id` I don't see any entities in Home Assistant using that ID. 

My config looks something like: 

```
sensor:   
  - platform: skolmat
    name: !secret skolmat_name
    url: !secret skolmat_url
    unique_id: skolmat_kids_school
```

And when filtering all my entities for `skolmat` I'm finding these:
* `sensor.Xxxxxx` where `Xxxx` is the school name I defined as a secret
* `switch.skolmat_integration_pre_release`
* `switch.skolmat_integration_pre_release`

I've tried removing the `sensor.Xxxx` (which itself works great and shows the correct food schedule), and restarted Home Assistant after each attempt. 

Could it be that there's something not working with the `unique_id` or perhaps that I'm not understanding how it's supposed to work? I would love to reference the skolmat entity by some other name that doesn't include the name of the school for privacy concerns and being able to share my HA config without exposing that kind of data.

* Running skolmat installed from HACS, version 1.3.0
* Home Assistant 2025.4.2

Thanks in advance!
