### ISSUE TITLE
More then one school

### ISSUE THREAD

**Issue by ekalle-swe** [Kaptensanders/skolmat#7]
Have 2 kids, going to 2 different schools, therefor I declared 2 sensors in configuration.yaml
Somehow it only adds the 2nd sensor as an entity. The first one is ignored. 
Is this a limitation or a bugg?

#
# Skolmat integration
#                    
sensor:                             
  - platform: skolmat                                                     
    name: Tage # Name of school here                                      
    rss: "https://skolmaten.se/kinnarummaskolan/rss/weeks" # your rss here
#                    
sensor:                              
  - platform: skolmat                                                        
    name: Algot # Name of school here                                        
    rss: "https://skolmaten.se/daltorpskolan-f6-k2/rss/weeks" # your rss here
#

**Comment by agent-ost** [comment]
@ekalle-swe My config looks like this and it works

```yaml
sensor:
  - platform: skolmat
    name: Nyvång
    rss: "https://skolmaten.se/nyvangskolan/rss/weeks/"
  - platform: skolmat
    name: Spyken
    rss: "https://skolmaten.se/spyken-gymnasieskola/rss/weeks/"
```
